apiVersion: v1
kind: Service
metadata:
  # Service da API para acesso local em clusters como Docker Desktop, Kind ou Minikube
  name: api
  namespace: tech-challenge
  labels:
    app: tech-challenge
    component: api
spec:
  type: NodePort
  selector:
    app: tech-challenge
    component: api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
