apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: tech-challenge
  labels:
    app: tech-challenge
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge
      component: api
  template:
    metadata:
      labels:
        app: tech-challenge
        component: api
    spec:
      containers:
        - name: api
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/tech-challenge-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: tech-challenge-config
            - secretRef:
                name: tech-challenge-secret
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-secret
                  key: ConnectionStrings__DefaultConnection
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
