apiVersion: v1
kind: Service
metadata:
  # Service interno do PostgreSQL, acessado apenas pela API dentro do cluster
  name: postgres
  namespace: tech-challenge
  labels:
    app: tech-challenge
    component: postgres
spec:
  type: ClusterIP
  selector:
    app: tech-challenge
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
