apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-db-secret
  namespace: tech-challenge
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: tech-challenge
---
apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-db
  namespace: tech-challenge
spec:
  selector:
    app: tech-challenge-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-db
  namespace: tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-db
  template:
    metadata:
      labels:
        app: tech-challenge-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-db-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
