apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-secret
  namespace: tech-challenge
  labels:
    app: tech-challenge
    component: secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: <replace-with-rds-postgres-password>
  Email__UserName: ""
  Email__Password: ""
  Jwt__Secret: <replace-with-strong-random-jwt-secret>
  ConnectionStrings__DefaultConnection: Host=<rds-postgres-host>.rds.amazonaws.com;Port=5432;Database=techchallenge;Username=postgres;Password=<replace-with-rds-postgres-password>
