apiVersion: v1
kind: Secret
metadata:
  # Dados sensíveis utilizados pelos containers
  name: tech-challenge-secret
  namespace: tech-challenge
  labels:
    app: tech-challenge
    component: secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  SMTP_USERNAME: smtp-user
  SMTP_PASSWORD: smtp-password
  Jwt__Secret: 3b45f6b4b1433e9fb87ec4bceef4501d
  ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=tech-challenge;Username=postgres;Password=postgres
